### PR TITLE
✨ Adding tecnodes

### PR DESCRIPTION
**Pull request by tecnodes-network**
www.tecnodes.network

### CODE REVIEW

**Comment by apoorvsadana** [comment]
Awesome! Can you please update the CLI version so that the explorer starts working. More details here - https://mirror.xyz/dashboard/edit/5y5OV_kiX9UJDW1HGc8mXcummpcgt4VpwjQRHMzDlFI

**Comment by tecnodes-network** [comment]
> Awesome! Can you please update the CLI version so that the explorer starts working. More details here - https://mirror.xyz/dashboard/edit/5y5OV_kiX9UJDW1HGc8mXcummpcgt4VpwjQRHMzDlFI

the link you provided is private, can't see it, but i do see an update, shall i only update the explorer?

**Comment by tecnodes-network** [comment]
> Awesome! Can you please update the CLI version so that the explorer starts working. More details here - https://mirror.xyz/dashboard/edit/5y5OV_kiX9UJDW1HGc8mXcummpcgt4VpwjQRHMzDlFI

i did following:

git checkout explorer_patch  
cargo build --release

killed and started:
./target/release/madara run

docker stop explorer container and:
./target/release/madara explorer

but still no data
http://explorer.madara.tecnodes.network:4000/

do i miss something?

**Comment by apoorvsadana** [comment]
Hey, sorry for the wrong link. Can you refer to this one - https://mirror.xyz/karnot.eth/5y5OV_kiX9UJDW1HGc8mXcummpcgt4VpwjQRHMzDlFI

**Comment by apoorvsadana** [comment]
Also, please follow the correct PR standards

**Comment by satman81** [comment]
> Also, please follow the correct PR standards

If i understand correctly i should just add /metrics in metrics endpoints or you mean something else?

**Pull request closed without merging**
