### PR TITLE
✨ Adding avail1

### PR DESCRIPTION
**Pull request by hosein-maleki**
Adding avail1 App Chain

### CODE REVIEW

**Comment by Zidroe** [comment]
Hello, sry for interupting but how did you get all 4 checks ?

**Comment by hosein-maleki** [comment]
> Hello, sry for interupting but how did you get all 4 checks ?

Your json file have extra spaces try to delete spaces using prettier

**Comment by Zidroe** [comment]
> > Hello, sry for interupting but how did you get all 4 checks ?
> 
> Your json file have extra spaces try to delete spaces using prettier

What does it mean bro, can you explain me please

**Comment by hosein-maleki** [comment]
> > > Hello, sry for interupting but how did you get all 4 checks ?
> > 
> > 
> > Your json file have extra spaces try to delete spaces using prettier
> 
> What does it mean bro, can you explain me please

Watch this video : https://www.youtube.com/watch?v=gnRPUG29RGA&t=1126s
This is persian language but you can follow steps

**Pull request merged**
