### PR TITLE
✨ Adding NomadValidator

### PR DESCRIPTION
**Pull request by nomad7617**

### CODE REVIEW

**Comment by apoorvsadana** [comment]
Sorry @nomad7617, I had to revert this commit as your explorer isn't working. Please update it.

**Comment by nomad7617** [comment]
Hello, @apoorvsadana the explorer is working now

**Comment by nomad7617** [comment]
Hello do I have to open a new PR?

**Comment by maxiaoxiong** [comment]
How can i check blocks sync is right? 
image

I request /blocks/1 report error.

**Comment by maxiaoxiong** [comment]
Can you help me @nomad7617 pls

**Comment by nomad7617** [comment]
> Can you help me @nomad7617 pls

Hello, you can do
git pull
cargo buil --release
Then when you run explorer add --host=ip

**Pull request merged**
