### PR TITLE
✨ Adding AstroNodes

### PR DESCRIPTION
**Pull request by Alping0**

### CODE REVIEW

**Comment by apoorvsadana** [comment]
The endpoints aren't accessible

**Comment by luvsourcandy** [comment]
> The endpoints aren't accessible

sir how to make endpoints accessible and configure explorer ( can see blocks ) in right way ?
i think we all having the same trouble above

another big problem is Madara consuming too much avail tokens ( ~3 AVL for 300 blocks for me ) my wallet doesnt have enough balance to keep it run so i must force to stop. We cant faucet too much tokens in discord ( 1 AVL every 180mins and thats not enough )

**Comment by luvsourcandy** [comment]
and how many blocks we need to confirm to sync ?
this is my screenshot, can you help me look into it if have any error pls . Thank you so much for help !

Ảnh chụp màn hình 2024-01-26 150054

**Comment by Alping0** [comment]
> The endpoints aren't accessible

Can you help me on that, how could i do endpoints accessible?

**Pull request closed without merging**
