### PR TITLE
✨ Adding Hexskrt

### PR DESCRIPTION
**Pull request by hexskrt**

### CODE REVIEW

**Comment by apoorvsadana** [comment]
Your explorer page opens up nginx. Please check.

**Comment by hexskrt** [comment]
fixed it, could you check again please?

**Comment by apoorvsadana** [comment]
still not working

**Comment by hexskrt** [comment]
https://explorer.madara.hexnodes.co

i've commit

**Comment by hexskrt** [comment]
oh it says always no connection, how to fix it? we just build with latest release

**Comment by hexskrt** [comment]
it should fixed, please check again one more time
image

**Pull request closed without merging**
